// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var UserItem$ReactHooksTemplate = require("./UserItem.bs.js");

var sampleUsers = /* :: */[
  /* record */[
    /* id */1,
    /* name */"User 1"
  ],
  /* :: */[
    /* record */[
      /* id */2,
      /* name */"User 2"
    ],
    /* :: */[
      /* record */[
        /* id */3,
        /* name */"User 3"
      ],
      /* :: */[
        /* record */[
          /* id */4,
          /* name */"User 4"
        ],
        /* [] */0
      ]
    ]
  ]
];

function OnlineUsersWrapper(Props) {
  var onlineUsers = List.map((function (u) {
          return React.createElement(UserItem$ReactHooksTemplate.make, {
                      user: u
                    });
        }), sampleUsers);
  var onlineUsersTitle = "Online users - " + String(List.length(sampleUsers));
  return React.createElement("div", {
              className: "onlineUsersWrapper"
            }, React.createElement("div", {
                  className: "sliderHeader"
                }, onlineUsersTitle), $$Array.of_list(onlineUsers));
}

var make = OnlineUsersWrapper;

exports.sampleUsers = sampleUsers;
exports.make = make;
/* react Not a pure module */
