// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function UserItem(Props) {
  var user = Props.user;
  return React.createElement("div", {
              className: "userInfo"
            }, React.createElement("div", {
                  className: "userImg"
                }, React.createElement("i", {
                      className: "far fa-user"
                    })), React.createElement("div", {
                  className: "userName"
                }, user[/* name */1]));
}

var make = UserItem;

exports.make = make;
/* react Not a pure module */
