// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function FeedItem(Props) {
  var todo = Props.todo;
  var match = todo[/* user */4];
  var userString = match !== undefined ? "@" + match[/* name */1] : "";
  var match$1 = todo[/* is_completed */2];
  var todoTextStyle = "labelContent" + (
    match$1 ? " completed" : ""
  );
  return React.createElement("li", undefined, React.createElement("div", {
                  className: "userInfoPublic",
                  title: userString
                }, userString), React.createElement("div", {
                  className: todoTextStyle
                }, React.createElement("div", undefined, todo[/* title */1])));
}

var make = FeedItem;

exports.make = make;
/* react Not a pure module */
