// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function TodoInput(Props) {
  Props.isPublic;
  return React.createElement("form", {
              className: "formInput"
            }, React.createElement("input", {
                  className: "input",
                  placeholder: "What needs to be done?"
                }), React.createElement("i", {
                  className: "inputMarker fa fa-angle-right"
                }));
}

var make = TodoInput;

exports.make = make;
/* react Not a pure module */
