// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var TodoInput$ReactHooksTemplate = require("./TodoInput.bs.js");
var TodoPrivateList$ReactHooksTemplate = require("./TodoPrivateList.bs.js");

function TodoPrivateWrapper(Props) {
  return React.createElement("div", {
              className: "todoWrapper"
            }, React.createElement("div", {
                  className: "sectionHeader"
                }, "Personal todos"), React.createElement(TodoInput$ReactHooksTemplate.make, {
                  isPublic: false
                }), React.createElement(TodoPrivateList$ReactHooksTemplate.make, { }));
}

var make = TodoPrivateWrapper;

exports.make = make;
/* react Not a pure module */
