// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var FeedItem$ReactHooksTemplate = require("./FeedItem.bs.js");

var sampleTodos = /* :: */[
  /* record */[
    /* id */1,
    /* title */"This is public todo 1",
    /* is_completed */false,
    /* is_public */true,
    /* user *//* record */[
      /* id */33,
      /* name */"someUser1"
    ]
  ],
  /* :: */[
    /* record */[
      /* id */2,
      /* title */"This is public todo 2",
      /* is_completed */false,
      /* is_public */true,
      /* user *//* record */[
        /* id */45,
        /* name */"someUser2"
      ]
    ],
    /* :: */[
      /* record */[
        /* id */3,
        /* title */"This is public todo 3",
        /* is_completed */false,
        /* is_public */true,
        /* user *//* record */[
          /* id */55,
          /* name */"someUser3"
        ]
      ],
      /* :: */[
        /* record */[
          /* id */4,
          /* title */"This is public todo 4",
          /* is_completed */false,
          /* is_public */true,
          /* user *//* record */[
            /* id */244,
            /* name */"someUser4"
          ]
        ],
        /* [] */0
      ]
    ]
  ]
];

function TodoPublicList(Props) {
  var todoList = List.map((function (t) {
          return React.createElement(FeedItem$ReactHooksTemplate.make, {
                      todo: t
                    });
        }), sampleTodos);
  var newTodosBanner = React.createElement("div", {
        className: "loadMoreSection"
      }, "New tasks have arrived!");
  var oldTodosButton = React.createElement("div", {
        className: "loadMoreSection"
      }, "Load older tasks");
  return React.createElement(React.Fragment, {
              children: React.createElement("div", {
                    className: "todoListWrapper"
                  }, newTodosBanner, React.createElement("ul", undefined, $$Array.of_list(todoList)), oldTodosButton)
            });
}

var make = TodoPublicList;

exports.sampleTodos = sampleTodos;
exports.make = make;
/* react Not a pure module */
