// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function todoToJs(param) {
  return {
          id: param[/* id */0],
          title: param[/* title */1],
          is_completed: param[/* is_completed */2],
          is_public: param[/* is_public */3],
          user: param[/* user */4]
        };
}

function todoFromJs(param) {
  return /* record */[
          /* id */param.id,
          /* title */param.title,
          /* is_completed */param.is_completed,
          /* is_public */param.is_public,
          /* user */param.user
        ];
}

exports.todoToJs = todoToJs;
exports.todoFromJs = todoFromJs;
/* No side effect */
