// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Navbar$ReactHooksTemplate = require("../Navbar.bs.js");

function Wrapper(Props) {
  return React.createElement("div", undefined, React.createElement(Navbar$ReactHooksTemplate.make, { }), React.createElement("div", undefined, "Hello world"));
}

var make = Wrapper;

exports.make = make;
/* react Not a pure module */
