// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var ApolloLinks = require("reason-apollo/src/ApolloLinks.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var ApolloInMemoryCache = require("reason-apollo/src/ApolloInMemoryCache.bs.js");

function makeApolloClient(token) {
  var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(undefined, undefined, /* () */0);
  var headers = Json_encode.object_(/* :: */[
        /* tuple */[
          "authorization",
          "Bearer " + token
        ],
        /* [] */0
      ]);
  var httpLink = ApolloLinks.createHttpLink("https://learn.hasura.io/graphql", undefined, undefined, Caml_option.some(headers), undefined, undefined, /* () */0);
  return ReasonApollo.createApolloClient(httpLink, inMemoryCache, undefined, undefined, undefined, undefined, /* () */0);
}

exports.makeApolloClient = makeApolloClient;
/* ApolloLinks Not a pure module */
