// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Navbar$ReactHooksTemplate = require("./Navbar.bs.js");
var ApolloClient$ReactHooksTemplate = require("./ApolloClient.bs.js");
var TodoPublicWrapper$ReactHooksTemplate = require("./todo/TodoPublicWrapper.bs.js");
var OnlineUsersWrapper$ReactHooksTemplate = require("./online-users/OnlineUsersWrapper.bs.js");
var TodoPrivateWrapper$ReactHooksTemplate = require("./todo/TodoPrivateWrapper.bs.js");

function App(Props) {
  var token = Props.token;
  ApolloClient$ReactHooksTemplate.makeApolloClient(token);
  return React.createElement("div", undefined, React.createElement(Navbar$ReactHooksTemplate.make, { }), React.createElement("div", {
                  className: "container-fluid p-left-right-0"
                }, React.createElement("div", {
                      className: "col-xs-12 col-md-9 p-left-right-0"
                    }, React.createElement("div", {
                          className: "col-xs-12 col-md-6 sliderMenu p-30"
                        }, React.createElement(TodoPrivateWrapper$ReactHooksTemplate.make, { })), React.createElement("div", {
                          className: "col-xs-12 col-md-6 sliderMenu p-30 bg-gray border-right"
                        }, React.createElement(TodoPublicWrapper$ReactHooksTemplate.make, { }))), React.createElement("div", {
                      className: "col-xs-12 col-md-3 p-left-right-0"
                    }, React.createElement("div", {
                          className: "col-xs-12 col-md-12 sliderMenu p-30 bg-gray"
                        }, React.createElement(OnlineUsersWrapper$ReactHooksTemplate.make, { })))));
}

var make = App;

exports.make = make;
/* react Not a pure module */
