// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Router$ReactHooksTemplate = require("./Router.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Router$ReactHooksTemplate.make, { }), "index");

/*  Not a pure module */
