// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Navbar(Props) {
  return React.createElement("nav", {
              className: "m-bottom-0 navbar navbar-default"
            }, React.createElement("div", {
                  className: "container-fluid"
                }, React.createElement("div", {
                      className: "navHeader navbar-header"
                    }, React.createElement("span", {
                          className: "navBrand navbar-brand"
                        }, "GraphQL Tutorial App"), React.createElement("ul", {
                          className: "nav navbar-nav navbar-right"
                        }, React.createElement("li", {
                              role: "presentation"
                            }, React.createElement("a", {
                                  role: "button",
                                  href: ""
                                }, React.createElement("button", {
                                      className: "btn-margin logoutBtn btn btn-primary",
                                      id: "qsLogoutBtn"
                                    }, "Log out")))))));
}

var make = Navbar;

exports.make = make;
/* react Not a pure module */
