// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function Router(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  var exit = 0;
  if (match) {
    if (match[0] === "login" && !match[1]) {
      return React.createElement("div", undefined, "Login");
    } else {
      exit = 1;
    }
  } else {
    return React.createElement("div", undefined, "Root");
  }
  if (exit === 1) {
    ReasonReactRouter.push("/");
    return React.createElement("div", undefined, "Root");
  }
  
}

var make = Router;

exports.make = make;
/* react Not a pure module */
