// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Login(Props) {
  return React.createElement("div", {
              className: "overlay"
            }, React.createElement("div", {
                  className: "overlay-content"
                }, React.createElement("div", {
                      className: "overlay-heading"
                    }, "Welcome to the GraphQL tutorial app"), React.createElement("div", {
                      className: "overlay-message"
                    }, "Please login to continue"), React.createElement("div", {
                      className: "overlay-action"
                    }, React.createElement("button", {
                          className: "btn-primary btn-margin btn loginBtn",
                          id: "qsLoginBtn"
                        }, "Log in"))));
}

var make = Login;

exports.make = make;
/* react Not a pure module */
