// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

function saveTokenToStorage(value) {
  localStorage.setItem("@learn.hasura.io:reason-apollo", value);
  return /* () */0;
}

function getTokenFromStorage(param) {
  return Caml_option.null_to_opt(localStorage.getItem("@learn.hasura.io:reason-apollo"));
}

exports.saveTokenToStorage = saveTokenToStorage;
exports.getTokenFromStorage = getTokenFromStorage;
/* No side effect */
